// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcdkyorxvtkmpgfspjiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjZGt5b3J4dnRrbXBnZnNwaml6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NTU3ODUsImV4cCI6MjA3MTMzMTc4NX0.omMU5LXXOppPFeOUqrOQ4Y3oD25dE5iW2TTC7UuawP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});